jbsub -queue x86_24h -mem 16g -out task1.train.out -err task1.train.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 1 --embedding_size 32 --hops 1 --epochs 2000 --match_feature_flag False
jbsub -queue x86_24h -mem 16g -out task1.train.mf.out -err task1.train.mf.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 1 --embedding_size 32 --hops 1 --epochs 2000
jbsub -queue x86_24h -mem 16g -out task2.train.out -err task2.train.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 2 --embedding_size 32 --hops 1 --epochs 2000 --match_feature_flag False
jbsub -queue x86_24h -mem 16g -out task2.train.mf.out -err task2.train.mf.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 2 --embedding_size 32 --hops 1 --epochs 2000
jbsub -queue x86_24h -mem 16g -out task3.train.4.out -err task3.train.4.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 3 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 4.0 --match_feature_flag False
jbsub -queue x86_24h -mem 16g -out task3.train.8.out -err task3.train.8.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 3 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 8.0 --match_feature_flag False
jbsub -queue x86_24h -mem 16g -out task3.train.16.out -err task3.train.16.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 3 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 16.0 --match_feature_flag False
jbsub -queue x86_24h -mem 16g -out task3.train.4.mf.out -err task3.train.4.mf.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 3 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 4.0
jbsub -queue x86_24h -mem 16g -out task3.train.8.mf.out -err task3.train.8.mf.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 3 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 8.0
jbsub -queue x86_24h -mem 16g -out task3.train.16.mf.out -err task3.train.16.mf.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 3 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 16.0
jbsub -queue x86_24h -mem 16g -out task4.train.out -err task4.train.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 4 --embedding_size 32 --hops 2 --epochs 2000 --match_feature_flag False
jbsub -queue x86_24h -mem 16g -out task5.train.4.out -err task5.train.4.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 5 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 4.0 --match_feature_flag False
jbsub -queue x86_24h -mem 16g -out task5.train.8.out -err task5.train.8.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 5 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 8.0 --match_feature_flag False
jbsub -queue x86_24h -mem 16g -out task5.train.16.out -err task5.train.16.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 5 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 16.0 --match_feature_flag False
jbsub -queue x86_24h -mem 16g -out task5.train.4.mf.out -err task5.train.4.mf.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 5 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 4.0
jbsub -queue x86_24h -mem 16g -out task5.train.8.mf.out -err task5.train.8.mf.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 5 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 8.0
jbsub -queue x86_24h -mem 16g -out task5.train.16.mf.out -err task5.train.16.mf.err /u/diraghu1/miniconda3/bin/python single_dialog.py --train True --task_id 5 --embedding_size 32 --hops 3 --epochs 2000  --loss_type  --loss_weight 16.0